Repository Big-Cow-King/PlayPal-Backend, pull requests merged in 2024-03, with the labels that each got.

#70 Fix/69 allow user to play multiple sports
  README.md
  accounts/migrations/0001_initial.py
  accounts/models.py
  accounts/serializers.py
  events/migrations/0001_initial.py
  events/models.py
  events/serializers.py
  notifications/migrations/0001_initial.py
Labels: bug

#71 #69 fixed none type error when sports is not passed in
  accounts/serializers.py
Labels: bug

#73 #72 fix the image update
  accounts/serializers.py
Labels: bug

#78 #77 Pagination is implemented with pagesize 20.
  README.md
  playpal_backend/settings.py
Labels: enhancement

#79 #75 Event search implmented
  playpal_backend/urls.py
  search/__init__.py
  search/admin.py
  search/apps.py
  search/migrations/__init__.py
  search/models.py
  search/tests.py
  search/urls.py
  search/views.py
Labels: enhancement

#80 #76 user profile search
  README.md
  search/urls.py
  search/views.py
Labels: enhancement

#81 #75 Updated search event logics
  README.md
  search/views.py
Labels: enhancement

#83 Updated Documentation for pagination
  README.md
Labels: documentation

#84 #82 Private event will not be fetched
  events/views.py
  search/views.py
Labels: bug

#86 #85 search bug fixed
  search/views.py
Labels: bug

#87 #77 Changed PageNumberPagination as default pagination class
  playpal_backend/settings.py
Labels: enhancement

#89 #88 Getting user by id would contain events info
  README.md
  accounts/detail_serializers.py
  accounts/views.py
  events/migrations/0001_initial.py
  events/models.py
  notifications/migrations/0001_initial.py
Labels: enhancement

#90 #7 Implement Delete functionality for notifications
  README.md
  notifications/urls.py
  notifications/views.py
Labels: enhancement

#91 #12 payment promotion
  README.md
  events/migrations/0001_initial.py
  events/models.py
  events/views.py
  payments/__init__.py
  payments/admin.py
  payments/apps.py
  payments/migrations/0001_initial.py
  payments/migrations/__init__.py
  payments/models.py
  payments/serializers.py
  payments/tests.py
  payments/urls.py
  payments/views.py
  playpal_backend/settings.py
  playpal_backend/urls.py
  requirements.txt
  search/views.py
Labels: enhancement

#92 #12 Hide SECRET
  payments/views.py
Labels: enhancement

#93 #12 Fixed README
  README.md
  payments/views.py
Labels: documentation

#94 #12 Fixed Update event promotion
  payments/views.py
Labels: enhancement

#96 #95 Fixed password changes when profile updates
  accounts/detail_serializers.py
  accounts/serializers.py
Labels: bug

#98 Update url payment to payments
  README.md
Labels: documentation

#99 #12 Now promotion will be cumulative
  payments/views.py
Labels: enhancement

#101 #100 Event that does not have image will now have default image
  events/migrations/0001_initial.py
  events/models.py
  uploads/events/attachments/placeholder.png
Labels: enhancement

#102 #7 Added unread noti count
  README.md
  notifications/views.py
Labels: enhancement
