Repository Big-Cow-King/PlayPal-Backend, pull requests merged in 2024-02, with the labels that each got.

#24 23 Fix: Add lib to resolve CORS error
  playpal_backend/settings.py
  requirements.txt
Labels: bug

#28 merge feature 1 create account and feature 2 login into main
  db.sqlite3
  playpal_backend/settings.py
  playpal_backend/urls.py
  registration/__init__.py
  registration/admin.py
  registration/apps.py
  registration/models.py
  registration/serializers.py
  registration/tests.py
  registration/urls.py
  registration/views.py
  requirements.txt
Labels: enhancement

#29 merge Feature/4 events into main
  events/__init__.py
  events/admin.py
  events/apps.py
  events/migrations/0001_initial.py
  events/migrations/__init__.py
  events/models.py
  events/serializers.py
  events/tests.py
  events/urls.py
  events/views.py
  playpal_backend/settings.py
  playpal_backend/urls.py
  requirements.txt
Labels: enhancement

#30 merge Feature/3 edit profile into main
  playpal_backend/settings.py
  playpal_backend/urls.py
  requirements.txt
  userprofile/__init__.py
  userprofile/admin.py
  userprofile/apps.py
  userprofile/migrations/0001_initial.py
  userprofile/migrations/0002_profile_email_product_profile_email_security_and_more.py
  userprofile/migrations/__init__.py
  userprofile/models.py
  userprofile/serializers.py
  userprofile/tests.py
  userprofile/urls.py
  userprofile/views.py
Labels: enhancement

#32 #31 Fixed event create required not necessary field
  events/serializers.py
Labels: bug

#33 #31 Fixed event create required not necessary field
  events/serializers.py
Labels: bug

#35 Feature/34 event image field
  events/migrations/0001_initial.py
  events/models.py
  events/serializers.py
  playpal_backend/settings.py
  playpal_backend/urls.py
Labels: enhancement

#37 #36 Image now can display correctly
  events/migrations/0001_initial.py
  events/models.py
  events/serializers.py
  playpal_backend/settings.py
Labels: bug

#38 #36 Fixed update remove img
  events/serializers.py
Labels: bug

#39 #3 update code for serializer
  userprofile/migrations/0001_initial.py
  userprofile/migrations/0002_profile_email_product_profile_email_security_and_more.py
  userprofile/serializers.py
  userprofile/urls.py
  userprofile/views.py
Labels: enhancement

#41 #3 implement get user profiles
  db.sqlite3
  userprofile/migrations/0001_initial.py
  userprofile/models.py
  userprofile/serializers.py
  userprofile/urls.py
  userprofile/views.py
Labels: enhancement

#42 Feature/3 edit profile
  userprofile/migrations/0001_initial.py
Labels: bug

#45 #43 Increase description words limit to 1000, content to unlimited
  events/migrations/0001_initial.py
  events/models.py
  events/serializers.py
Labels: enhancement

#50 #46 fixed join event 500 error. Now return expected information
  events/views.py
Labels: bug

#49 #48 fixed create event 500 error.
  events/serializers.py
Labels: bug

#51 #44 Replace user.auth with actual user
  events/migrations/0001_initial.py
  events/models.py
Labels: enhancement

#52 #47 add event hidden feature
  events/migrations/0001_initial.py
  events/models.py
  events/serializers.py
Labels: enhancement

#54 #19 added feature: quit event
  events/urls.py
  events/views.py
Labels: enhancement

#53 #17 added feature: cancel/delete event
  events/urls.py
  events/views.py
Labels: enhancement

#56 #55 fixed users rollback to user instance instead of profile
  events/migrations/0001_initial.py
  events/models.py
  events/serializers.py
Labels: bug

#62 Added docs
  README.md
  accounts/urls.py
Labels: documentation

#63 Rename notification to notifications for unify format
  README.md
  events/serializers.py
  notifications/__init__.py
  notifications/admin.py
  notifications/apps.py
  notifications/migrations/0001_initial.py
  notifications/migrations/__init__.py
  notifications/models.py
  notifications/serializers.py
  notifications/tests.py
  notifications/urls.py
  notifications/views.py
  playpal_backend/settings.py
  playpal_backend/urls.py
Labels: documentation, good first issue

#64 #7 Update reminder notification with more clear information
  README.md
  events/serializers.py
  notifications/migrations/0001_initial.py
  notifications/models.py
  notifications/serializers.py
  notifications/urls.py
  notifications/views.py
Labels: documentation, enhancement

#66 #65 Owner of an event will automatically add as admin
  events/serializers.py
Labels: enhancement

#68 #67 Added capacity check for event when a new player joins
  events/views.py
Labels: bug
